/* ── Algerian Wilayas with Communes & Postal Codes ── */
/* Each wilaya has an array of communes, each with a name and postal code */

export interface Commune {
  name: string;
  postalCode: string;
}

export interface WilayaCommunes {
  wilaya: string;
  communes: Commune[];
}

export const ALGERIA_DATA: WilayaCommunes[] = [
  {
    wilaya: "Adrar",
    communes: [
      { name: "Adrar", postalCode: "01000" },
      { name: "Timimoun", postalCode: "01001" },
      { name: "Reggane", postalCode: "01002" },
      { name: "In Salah", postalCode: "01003" },
      { name: "Aoulef", postalCode: "01004" },
      { name: "Tsabit", postalCode: "01005" },
      { name: "Zaouiet Kounta", postalCode: "01006" },
      { name: "Bordj Badji Mokhtar", postalCode: "01007" },
      { name: "In Guezzam", postalCode: "01008" },
      { name: "Tit", postalCode: "01009" },
      { name: "Fenoughil", postalCode: "01010" },
      { name: "Charouine", postalCode: "01011" },
      { name: "Aougrout", postalCode: "01012" },
      { name: "Tamest", postalCode: "01013" },
      { name: "Deldoul", postalCode: "01014" },
      { name: "Ksar Kaddour", postalCode: "01015" },
      { name: "Ouled Ahmed Timmi", postalCode: "01016" },
      { name: "Sali", postalCode: "01017" },
      { name: "Tamest", postalCode: "01018" },
      { name: "Bouda", postalCode: "01019" },
    ],
  },
  {
    wilaya: "Chlef",
    communes: [
      { name: "Chlef", postalCode: "02000" },
      { name: "Ténès", postalCode: "02001" },
      { name: "El Karimia", postalCode: "02002" },
      { name: "El Marsa", postalCode: "02003" },
      { name: "Ouled Fares", postalCode: "02004" },
      { name: "Beni Haoua", postalCode: "02005" },
      { name: "Boukadir", postalCode: "02006" },
      { name: "Oued Fodda", postalCode: "02007" },
      { name: "El Hadjadj", postalCode: "02008" },
      { name: "Taougrit", postalCode: "02009" },
      { name: "Beni Rached", postalCode: "02010" },
      { name: "Abou El Hassan", postalCode: "02011" },
      { name: "Chettia", postalCode: "02012" },
      { name: "Moussadek", postalCode: "02013" },
      { name: "Sendjas", postalCode: "02014" },
      { name: "Oued Sly", postalCode: "02015" },
    ],
  },
  {
    wilaya: "Laghouat",
    communes: [
      { name: "Laghouat", postalCode: "03000" },
      { name: "Aflou", postalCode: "03001" },
      { name: "Ksar El Hirane", postalCode: "03002" },
      { name: "El Ghicha", postalCode: "03003" },
      { name: "Hassi R'Mel", postalCode: "03004" },
      { name: "Ain Madhi", postalCode: "03005" },
      { name: "Brida", postalCode: "03006" },
      { name: "Tadjmout", postalCode: "03007" },
      { name: "Sidi Makhlouf", postalCode: "03008" },
      { name: "Hassi Delaa", postalCode: "03009" },
      { name: "Gueltat Sidi Saad", postalCode: "03010" },
    ],
  },
  {
    wilaya: "Oum El Bouaghi",
    communes: [
      { name: "Oum El Bouaghi", postalCode: "04000" },
      { name: "Ain Beida", postalCode: "04001" },
      { name: "Ain M'lila", postalCode: "04002" },
      { name: "Ain Fakroun", postalCode: "04003" },
      { name: "Ksar Sbahi", postalCode: "04004" },
      { name: "Sigus", postalCode: "04005" },
      { name: "Meskiana", postalCode: "04006" },
      { name: "Dhalaa", postalCode: "04007" },
      { name: "Ain Babouche", postalCode: "04008" },
      { name: "Ain Kercha", postalCode: "04009" },
      { name: "Fkirina", postalCode: "04010" },
      { name: "Souk Naamane", postalCode: "04011" },
    ],
  },
  {
    wilaya: "Batna",
    communes: [
      { name: "Batna", postalCode: "05000" },
      { name: "Barika", postalCode: "05001" },
      { name: "Ain Touta", postalCode: "05002" },
      { name: "N'Gaous", postalCode: "05003" },
      { name: "Merouana", postalCode: "05004" },
      { name: "Tazoult", postalCode: "05005" },
      { name: "Seggana", postalCode: "05006" },
      { name: "Timgad", postalCode: "05007" },
      { name: "El Madher", postalCode: "05008" },
      { name: "Ain Djasser", postalCode: "05009" },
      { name: "Menaa", postalCode: "05010" },
      { name: "Ichemoul", postalCode: "05011" },
      { name: "Tkout", postalCode: "05012" },
      { name: "Ras El Aioun", postalCode: "05013" },
      { name: "Oued Chaaba", postalCode: "05014" },
      { name: "Chemora", postalCode: "05015" },
      { name: "Fesdis", postalCode: "05016" },
      { name: "Seriana", postalCode: "05017" },
      { name: "Zana", postalCode: "05018" },
      { name: "Talkhamt", postalCode: "05019" },
    ],
  },
  {
    wilaya: "Béjaïa",
    communes: [
      { name: "Béjaïa", postalCode: "06000" },
      { name: "Akbou", postalCode: "06001" },
      { name: "Sidi Aich", postalCode: "06002" },
      { name: "Amizour", postalCode: "06003" },
      { name: "El Kseur", postalCode: "06004" },
      { name: "Kherrata", postalCode: "06005" },
      { name: "Tichy", postalCode: "06006" },
      { name: "Aokas", postalCode: "06007" },
      { name: "Tazmalt", postalCode: "06008" },
      { name: "Seddouk", postalCode: "06009" },
      { name: "Ighil Ali", postalCode: "06010" },
      { name: "Darguina", postalCode: "06011" },
      { name: "Chemini", postalCode: "06012" },
      { name: "Souk El Tenine", postalCode: "06013" },
      { name: "Toudja", postalCode: "06014" },
      { name: "Ifri Ouzellaguen", postalCode: "06015" },
      { name: "Adekar", postalCode: "06016" },
      { name: "Barbacha", postalCode: "06017" },
      { name: "Tibane", postalCode: "06018" },
      { name: "Tamridjet", postalCode: "06019" },
    ],
  },
  {
    wilaya: "Biskra",
    communes: [
      { name: "Biskra", postalCode: "07000" },
      { name: "Tolga", postalCode: "07001" },
      { name: "Ouled Djellal", postalCode: "07002" },
      { name: "Sidi Okba", postalCode: "07003" },
      { name: "Djemorah", postalCode: "07004" },
      { name: "Zeribet El Oued", postalCode: "07005" },
      { name: "El Kantara", postalCode: "07006" },
      { name: "Sidi Khaled", postalCode: "07007" },
      { name: "Foughala", postalCode: "07008" },
      { name: "Ourlal", postalCode: "07009" },
      { name: "Lioua", postalCode: "07010" },
      { name: "Doucen", postalCode: "07011" },
      { name: "Ain Naga", postalCode: "07012" },
      { name: "M'Chounche", postalCode: "07013" },
      { name: "El Outaya", postalCode: "07014" },
    ],
  },
  {
    wilaya: "Béchar",
    communes: [
      { name: "Béchar", postalCode: "08000" },
      { name: "Abadla", postalCode: "08001" },
      { name: "Beni Ounif", postalCode: "08002" },
      { name: "Beni Abbes", postalCode: "08003" },
      { name: "Kenadsa", postalCode: "08004" },
      { name: "Taghit", postalCode: "08005" },
      { name: "Igli", postalCode: "08006" },
      { name: "Lahmar", postalCode: "08007" },
      { name: "Meridja", postalCode: "08008" },
      { name: "Mechraa Houari", postalCode: "08009" },
      { name: "Mougheul", postalCode: "08010" },
    ],
  },
  {
    wilaya: "Blida",
    communes: [
      { name: "Blida", postalCode: "09000" },
      { name: "Boufarik", postalCode: "09001" },
      { name: "Bougara", postalCode: "09002" },
      { name: "Mouzaia", postalCode: "09003" },
      { name: "El Affroun", postalCode: "09004" },
      { name: "Ouled Yaïch", postalCode: "09005" },
      { name: "Bouinan", postalCode: "09006" },
      { name: "Chréa", postalCode: "09007" },
      { name: "Beni Mered", postalCode: "09008" },
      { name: "Oued El Alleug", postalCode: "09009" },
      { name: "Meftah", postalCode: "09010" },
      { name: "Guerrouaou", postalCode: "09011" },
      { name: "Soumaa", postalCode: "09012" },
      { name: "Larbaa", postalCode: "09013" },
      { name: "Hammam Melouane", postalCode: "09014" },
      { name: "Chiffa", postalCode: "09015" },
      { name: "Oued Djer", postalCode: "09016" },
    ],
  },
  {
    wilaya: "Bouira",
    communes: [
      { name: "Bouira", postalCode: "10000" },
      { name: "Lakhdaria", postalCode: "10001" },
      { name: "Sour El Ghozlane", postalCode: "10002" },
      { name: "M'Chedallah", postalCode: "10003" },
      { name: "Ain Bessem", postalCode: "10004" },
      { name: "Kadiria", postalCode: "10005" },
      { name: "Bordj Okhriss", postalCode: "10006" },
      { name: "Bechloul", postalCode: "10007" },
      { name: "El Hachimia", postalCode: "10008" },
      { name: "Haizer", postalCode: "10009" },
      { name: "Taghzout", postalCode: "10010" },
      { name: "Aghbalou", postalCode: "10011" },
      { name: "El Adjiba", postalCode: "10012" },
      { name: "Bouderbala", postalCode: "10013" },
    ],
  },
  {
    wilaya: "Tamanrasset",
    communes: [
      { name: "Tamanrasset", postalCode: "11000" },
      { name: "In Salah", postalCode: "11001" },
      { name: "In Guezzam", postalCode: "11002" },
      { name: "Abalessa", postalCode: "11003" },
      { name: "Ideles", postalCode: "11004" },
      { name: "Tazrouk", postalCode: "11005" },
      { name: "In Amguel", postalCode: "11006" },
    ],
  },
  {
    wilaya: "Tébessa",
    communes: [
      { name: "Tébessa", postalCode: "12000" },
      { name: "Bir El Ater", postalCode: "12001" },
      { name: "Cheria", postalCode: "12002" },
      { name: "El Aouinet", postalCode: "12003" },
      { name: "El Malabiod", postalCode: "12004" },
      { name: "Ouenza", postalCode: "12005" },
      { name: "El Kouif", postalCode: "12006" },
      { name: "Negrine", postalCode: "12007" },
      { name: "Morsott", postalCode: "12008" },
      { name: "Bekkaria", postalCode: "12009" },
      { name: "Boulhaf Dyr", postalCode: "12010" },
      { name: "Hammamet", postalCode: "12011" },
    ],
  },
  {
    wilaya: "Tlemcen",
    communes: [
      { name: "Tlemcen", postalCode: "13000" },
      { name: "Maghnia", postalCode: "13001" },
      { name: "Ghazaouet", postalCode: "13002" },
      { name: "Remchi", postalCode: "13003" },
      { name: "Nedroma", postalCode: "13004" },
      { name: "Sebdou", postalCode: "13005" },
      { name: "Beni Saf", postalCode: "13006" },
      { name: "Hennaya", postalCode: "13007" },
      { name: "Mansourah", postalCode: "13008" },
      { name: "Chetouane", postalCode: "13009" },
      { name: "Ain Temouchent", postalCode: "13010" },
      { name: "Bab El Assa", postalCode: "13011" },
      { name: "Ouled Mimoun", postalCode: "13012" },
      { name: "Ain Fezza", postalCode: "13013" },
      { name: "Honaïne", postalCode: "13014" },
      { name: "Beni Boussaid", postalCode: "13015" },
      { name: "Fellaoucene", postalCode: "13016" },
      { name: "Sidi Djillali", postalCode: "13017" },
    ],
  },
  {
    wilaya: "Tiaret",
    communes: [
      { name: "Tiaret", postalCode: "14000" },
      { name: "Frenda", postalCode: "14001" },
      { name: "Ksar Chellala", postalCode: "14002" },
      { name: "Sougueur", postalCode: "14003" },
      { name: "Ain Deheb", postalCode: "14004" },
      { name: "Mahdia", postalCode: "14005" },
      { name: "Oued Lilli", postalCode: "14006" },
      { name: "Rahouia", postalCode: "14007" },
      { name: "Mechraa Sfa", postalCode: "14008" },
      { name: "Medroussa", postalCode: "14009" },
      { name: "Meghila", postalCode: "14010" },
      { name: "Hamadia", postalCode: "14011" },
    ],
  },
  {
    wilaya: "Tizi Ouzou",
    communes: [
      { name: "Tizi Ouzou", postalCode: "15000" },
      { name: "Azazga", postalCode: "15001" },
      { name: "Draa Ben Khedda", postalCode: "15002" },
      { name: "Draa El Mizan", postalCode: "15003" },
      { name: "Ain El Hammam", postalCode: "15004" },
      { name: "Larbaa Nath Irathen", postalCode: "15005" },
      { name: "Boghni", postalCode: "15006" },
      { name: "Bouzguene", postalCode: "15007" },
      { name: "Iferhouene", postalCode: "15008" },
      { name: "Mekla", postalCode: "15009" },
      { name: "Ouaguenoun", postalCode: "15010" },
      { name: "Tigzirt", postalCode: "15011" },
      { name: "Ouadhias", postalCode: "15012" },
      { name: "Azzefoun", postalCode: "15013" },
      { name: "Makouda", postalCode: "15014" },
      { name: "Beni Douala", postalCode: "15015" },
      { name: "Beni Yenni", postalCode: "15016" },
      { name: "Iflissen", postalCode: "15017" },
      { name: "Tirmitine", postalCode: "15018" },
      { name: "Maatkas", postalCode: "15019" },
    ],
  },
  {
    wilaya: "Alger",
    communes: [
      { name: "Alger Centre", postalCode: "16000" },
      { name: "Sidi M'Hamed", postalCode: "16001" },
      { name: "El Madania", postalCode: "16002" },
      { name: "Belouizdad", postalCode: "16003" },
      { name: "Bab El Oued", postalCode: "16004" },
      { name: "Bologhine", postalCode: "16005" },
      { name: "Oued Smar", postalCode: "16006" },
      { name: "Bourouba", postalCode: "16007" },
      { name: "Hussein Dey", postalCode: "16008" },
      { name: "Kouba", postalCode: "16009" },
      { name: "Bachdjerrah", postalCode: "16010" },
      { name: "El Harrach", postalCode: "16011" },
      { name: "Baraki", postalCode: "16012" },
      { name: "Oued Koriche", postalCode: "16013" },
      { name: "Bir Mourad Raïs", postalCode: "16014" },
      { name: "El Biar", postalCode: "16015" },
      { name: "Bouzareah", postalCode: "16016" },
      { name: "Birkhadem", postalCode: "16017" },
      { name: "El Mouradia", postalCode: "16018" },
      { name: "Hydra", postalCode: "16019" },
      { name: "Ben Aknoun", postalCode: "16020" },
      { name: "Dely Ibrahim", postalCode: "16021" },
      { name: "Bab Ezzouar", postalCode: "16022" },
      { name: "Dar El Beida", postalCode: "16023" },
      { name: "Rouiba", postalCode: "16024" },
      { name: "Ain Taya", postalCode: "16025" },
      { name: "Bordj El Kiffan", postalCode: "16026" },
      { name: "El Mohammadia", postalCode: "16027" },
      { name: "Mohammadia", postalCode: "16028" },
      { name: "Reghaia", postalCode: "16029" },
      { name: "Ain Benian", postalCode: "16030" },
      { name: "Staoueli", postalCode: "16031" },
      { name: "Zeralda", postalCode: "16032" },
      { name: "Cheraga", postalCode: "16033" },
      { name: "El Achour", postalCode: "16034" },
      { name: "Draria", postalCode: "16035" },
      { name: "Douera", postalCode: "16036" },
      { name: "Baba Hassen", postalCode: "16037" },
      { name: "Khraicia", postalCode: "16038" },
      { name: "Saoula", postalCode: "16039" },
      { name: "Tessala El Merdja", postalCode: "16040" },
      { name: "Les Eucalyptus", postalCode: "16041" },
      { name: "Heraoua", postalCode: "16042" },
    ],
  },
  {
    wilaya: "Djelfa",
    communes: [
      { name: "Djelfa", postalCode: "17000" },
      { name: "Ain Oussera", postalCode: "17001" },
      { name: "Messaad", postalCode: "17002" },
      { name: "Hassi Bahbah", postalCode: "17003" },
      { name: "Charef", postalCode: "17004" },
      { name: "Moudjbara", postalCode: "17005" },
      { name: "Djelfa", postalCode: "17006" },
      { name: "Ain El Ibel", postalCode: "17007" },
      { name: "Birine", postalCode: "17008" },
      { name: "Faidh El Botma", postalCode: "17009" },
      { name: "Dar Chioukh", postalCode: "17010" },
      { name: "Hassi El Euch", postalCode: "17011" },
      { name: "El Idrissia", postalCode: "17012" },
    ],
  },
  {
    wilaya: "Jijel",
    communes: [
      { name: "Jijel", postalCode: "18000" },
      { name: "El Milia", postalCode: "18001" },
      { name: "Taher", postalCode: "18002" },
      { name: "Chekfa", postalCode: "18003" },
      { name: "Texenna", postalCode: "18004" },
      { name: "Ziama Mansouriah", postalCode: "18005" },
      { name: "El Ancer", postalCode: "18006" },
      { name: "Settara", postalCode: "18007" },
      { name: "Kaous", postalCode: "18008" },
      { name: "El Aouana", postalCode: "18009" },
      { name: "Oudjana", postalCode: "18010" },
      { name: "Sidi Marouf", postalCode: "18011" },
      { name: "Djimla", postalCode: "18012" },
    ],
  },
  {
    wilaya: "Sétif",
    communes: [
      { name: "Sétif", postalCode: "19000" },
      { name: "El Eulma", postalCode: "19001" },
      { name: "Ain Oulmene", postalCode: "19002" },
      { name: "Bougaa", postalCode: "19003" },
      { name: "Ain Arnat", postalCode: "19004" },
      { name: "Ain El Kebira", postalCode: "19005" },
      { name: "Beni Aziz", postalCode: "19006" },
      { name: "Bouandas", postalCode: "19007" },
      { name: "Guenzet", postalCode: "19008" },
      { name: "Hammam Soukhna", postalCode: "19009" },
      { name: "Ksar El Abtal", postalCode: "19010" },
      { name: "Ain Azel", postalCode: "19011" },
      { name: "Babor", postalCode: "19012" },
      { name: "Djemila", postalCode: "19013" },
      { name: "Maoklane", postalCode: "19014" },
      { name: "Salah Bey", postalCode: "19015" },
      { name: "Ain Brahim", postalCode: "19016" },
    ],
  },
  {
    wilaya: "Saïda",
    communes: [
      { name: "Saïda", postalCode: "20000" },
      { name: "Ain El Hadjar", postalCode: "20001" },
      { name: "Youb", postalCode: "20002" },
      { name: "Ouled Brahim", postalCode: "20003" },
      { name: "Hassasna", postalCode: "20004" },
      { name: "Sidi Boubekeur", postalCode: "20005" },
      { name: "El Hassasna", postalCode: "20006" },
      { name: "Moulay Larbi", postalCode: "20007" },
      { name: "Doui Thabet", postalCode: "20008" },
    ],
  },
  {
    wilaya: "Skikda",
    communes: [
      { name: "Skikda", postalCode: "21000" },
      { name: "Azzaba", postalCode: "21001" },
      { name: "El Harrouch", postalCode: "21002" },
      { name: "Collo", postalCode: "21003" },
      { name: "Tamalous", postalCode: "21004" },
      { name: "Ain Kechra", postalCode: "21005" },
      { name: "Ramdane Djamel", postalCode: "21006" },
      { name: "El Hadaiek", postalCode: "21007" },
      { name: "Ben Azzouz", postalCode: "21008" },
      { name: "Sidi Mezghiche", postalCode: "21009" },
      { name: "Oued Z'hor", postalCode: "21010" },
      { name: "Zitouna", postalCode: "21011" },
      { name: "Salah Bouchaour", postalCode: "21012" },
    ],
  },
  {
    wilaya: "Sidi Bel Abbès",
    communes: [
      { name: "Sidi Bel Abbès", postalCode: "22000" },
      { name: "Telagh", postalCode: "22001" },
      { name: "Ain El Berd", postalCode: "22002" },
      { name: "Ben Badis", postalCode: "22003" },
      { name: "Sfisef", postalCode: "22004" },
      { name: "Tessala", postalCode: "22005" },
      { name: "Mostefa Ben Brahim", postalCode: "22006" },
      { name: "Ras El Ma", postalCode: "22007" },
      { name: "Marhoum", postalCode: "22008" },
      { name: "Sidi Ali Boussidi", postalCode: "22009" },
      { name: "Sidi Lahcene", postalCode: "22010" },
      { name: "Merine", postalCode: "22011" },
    ],
  },
  {
    wilaya: "Annaba",
    communes: [
      { name: "Annaba", postalCode: "23000" },
      { name: "El Bouni", postalCode: "23001" },
      { name: "El Hadjar", postalCode: "23002" },
      { name: "Berrahal", postalCode: "23003" },
      { name: "Ain El Berda", postalCode: "23004" },
      { name: "Seraidi", postalCode: "23005" },
      { name: "Chetaibi", postalCode: "23006" },
      { name: "Oued El Aneb", postalCode: "23007" },
      { name: "Cheurfa", postalCode: "23008" },
      { name: "El Eulma", postalCode: "23009" },
      { name: "Treat", postalCode: "23010" },
    ],
  },
  {
    wilaya: "Guelma",
    communes: [
      { name: "Guelma", postalCode: "24000" },
      { name: "Oued Zenati", postalCode: "24001" },
      { name: "Bouchegouf", postalCode: "24002" },
      { name: "Hammam Debagh", postalCode: "24003" },
      { name: "Héliopolis", postalCode: "24004" },
      { name: "Ain Makhlouf", postalCode: "24005" },
      { name: "Ain Sandel", postalCode: "24006" },
      { name: "Khezara", postalCode: "24007" },
      { name: "Nechmaya", postalCode: "24008" },
      { name: "Houari Boumediene", postalCode: "24009" },
      { name: "Hammam N'Bails", postalCode: "24010" },
      { name: "Medjez Amar", postalCode: "24011" },
    ],
  },
  {
    wilaya: "Constantine",
    communes: [
      { name: "Constantine", postalCode: "25000" },
      { name: "El Khroub", postalCode: "25001" },
      { name: "Ain Smara", postalCode: "25002" },
      { name: "Hamma Bouziane", postalCode: "25003" },
      { name: "Didouche Mourad", postalCode: "25004" },
      { name: "Zighoud Youcef", postalCode: "25005" },
      { name: "Ain Abid", postalCode: "25006" },
      { name: "Beni Hamidane", postalCode: "25007" },
      { name: "Ouled Rahmoune", postalCode: "25008" },
      { name: "Ibn Ziad", postalCode: "25009" },
      { name: "Messaoud Boudjeriou", postalCode: "25010" },
      { name: "Ali Mendjeli", postalCode: "25011" },
    ],
  },
  {
    wilaya: "Médéa",
    communes: [
      { name: "Médéa", postalCode: "26000" },
      { name: "Berrouaghia", postalCode: "26001" },
      { name: "Ksar El Boukhari", postalCode: "26002" },
      { name: "Tablat", postalCode: "26003" },
      { name: "Beni Slimane", postalCode: "26004" },
      { name: "El Omaria", postalCode: "26005" },
      { name: "Ouamri", postalCode: "26006" },
      { name: "Chahbounia", postalCode: "26007" },
      { name: "Ouled Derraji", postalCode: "26008" },
      { name: "Souagui", postalCode: "26009" },
      { name: "Si Mahdjoub", postalCode: "26010" },
      { name: "Damiat", postalCode: "26011" },
    ],
  },
  {
    wilaya: "Mostaganem",
    communes: [
      { name: "Mostaganem", postalCode: "27000" },
      { name: "Ain Tedles", postalCode: "27001" },
      { name: "Sidi Ali", postalCode: "27002" },
      { name: "Ain Nouissy", postalCode: "27003" },
      { name: "Hassi Maameche", postalCode: "27004" },
      { name: "Kheir Eddine", postalCode: "27005" },
      { name: "Mazagran", postalCode: "27006" },
      { name: "Sidi Lakhdar", postalCode: "27007" },
      { name: "Achaacha", postalCode: "27008" },
      { name: "Bouguirat", postalCode: "27009" },
      { name: "Mesra", postalCode: "27010" },
      { name: "Ouled Maalah", postalCode: "27011" },
    ],
  },
  {
    wilaya: "M'sila",
    communes: [
      { name: "M'sila", postalCode: "28000" },
      { name: "Bou Saada", postalCode: "28001" },
      { name: "Ain El Melh", postalCode: "28002" },
      { name: "Sidi Aissa", postalCode: "28003" },
      { name: "Hammam Dalaa", postalCode: "28004" },
      { name: "Magra", postalCode: "28005" },
      { name: "Khoubana", postalCode: "28006" },
      { name: "Ouled Sidi Brahim", postalCode: "28007" },
      { name: "Ain El Hadjel", postalCode: "28008" },
      { name: "Chellal", postalCode: "28009" },
      { name: "Ouled Derradj", postalCode: "28010" },
      { name: "Ben Srour", postalCode: "28011" },
      { name: "Medjedel", postalCode: "28012" },
      { name: "Benzouh", postalCode: "28013" },
    ],
  },
  {
    wilaya: "Mascara",
    communes: [
      { name: "Mascara", postalCode: "29000" },
      { name: "Sig", postalCode: "29001" },
      { name: "Mohammadia", postalCode: "29002" },
      { name: "Ain Fares", postalCode: "29003" },
      { name: "Oued Taria", postalCode: "29004" },
      { name: "Tighennif", postalCode: "29005" },
      { name: "Ain Fekan", postalCode: "29006" },
      { name: "Oued El Abtal", postalCode: "29007" },
      { name: "Ghriss", postalCode: "29008" },
      { name: "Zahana", postalCode: "29009" },
      { name: "Bou Hanifia", postalCode: "29010" },
      { name: "El Bordj", postalCode: "29011" },
      { name: "Khalouia", postalCode: "29012" },
      { name: "Maoussa", postalCode: "29013" },
    ],
  },
  {
    wilaya: "Ouargla",
    communes: [
      { name: "Ouargla", postalCode: "30000" },
      { name: "Touggourt", postalCode: "30001" },
      { name: "Hassi Messaoud", postalCode: "30002" },
      { name: "Ghardaia", postalCode: "30003" },
      { name: "El Hadjira", postalCode: "30004" },
      { name: "Taibet", postalCode: "30005" },
      { name: "Temacine", postalCode: "30006" },
      { name: "Megarine", postalCode: "30007" },
      { name: "N'Goussa", postalCode: "30008" },
      { name: "Sidi Khouiled", postalCode: "30009" },
      { name: "Rouissat", postalCode: "30010" },
      { name: "El Alia", postalCode: "30011" },
      { name: "Zaouia El Abidia", postalCode: "30012" },
    ],
  },
  {
    wilaya: "Oran",
    communes: [
      { name: "Oran", postalCode: "31000" },
      { name: "Bir El Djir", postalCode: "31001" },
      { name: "Es Senia", postalCode: "31002" },
      { name: "Ain Turk", postalCode: "31003" },
      { name: "Arzew", postalCode: "31004" },
      { name: "Bethioua", postalCode: "31005" },
      { name: "Oued Tlelat", postalCode: "31006" },
      { name: "Ain El Kerma", postalCode: "31007" },
      { name: "Bousfer", postalCode: "31008" },
      { name: "El Braya", postalCode: "31009" },
      { name: "Hassi Bounif", postalCode: "31010" },
      { name: "El Kerma", postalCode: "31011" },
      { name: "Boutlelis", postalCode: "31012" },
      { name: "Mers El Kébir", postalCode: "31013" },
      { name: "Ain El Bya", postalCode: "31014" },
      { name: "Hassi Mefsoukh", postalCode: "31015" },
      { name: "Sidi Chahmi", postalCode: "31016" },
      { name: "Ben Freha", postalCode: "31017" },
      { name: "El Ancor", postalCode: "31018" },
      { name: "Misserghin", postalCode: "31019" },
      { name: "Ain El Kerma", postalCode: "31020" },
      { name: "Bousfer", postalCode: "31021" },
    ],
  },
  {
    wilaya: "El Bayadh",
    communes: [
      { name: "El Bayadh", postalCode: "32000" },
      { name: "Bougtob", postalCode: "32001" },
      { name: "Brezina", postalCode: "32002" },
      { name: "Labiodh Sidi Cheikh", postalCode: "32003" },
      { name: "Ain El Orak", postalCode: "32004" },
      { name: "Rogassa", postalCode: "32005" },
      { name: "Chellala", postalCode: "32006" },
      { name: "Boualem", postalCode: "32007" },
      { name: "Stidia", postalCode: "32008" },
      { name: "Ghassoul", postalCode: "32009" },
    ],
  },
  {
    wilaya: "Illizi",
    communes: [
      { name: "Illizi", postalCode: "33000" },
      { name: "Djanet", postalCode: "33001" },
      { name: "In Amenas", postalCode: "33002" },
      { name: "Bordj Omar Driss", postalCode: "33003" },
      { name: "Debdeb", postalCode: "33004" },
    ],
  },
  {
    wilaya: "Bordj Bou Arréridj",
    communes: [
      { name: "Bordj Bou Arréridj", postalCode: "34000" },
      { name: "Ras El Oued", postalCode: "34001" },
      { name: "Bir Kasdali", postalCode: "34002" },
      { name: "Mansourah", postalCode: "34003" },
      { name: "Medjana", postalCode: "34004" },
      { name: "El Achir", postalCode: "34005" },
      { name: "Djaafra", postalCode: "34006" },
      { name: "Ain Taghrout", postalCode: "34007" },
      { name: "Bordj Ghedir", postalCode: "34008" },
      { name: "Hasnaoua", postalCode: "34009" },
      { name: "Bordj Zemoura", postalCode: "34010" },
      { name: "Sidi Embarek", postalCode: "34011" },
    ],
  },
  {
    wilaya: "Boumerdès",
    communes: [
      { name: "Boumerdès", postalCode: "35000" },
      { name: "Boudouaou", postalCode: "35001" },
      { name: "Dellys", postalCode: "35002" },
      { name: "Khemis El Khechna", postalCode: "35003" },
      { name: "Bordj Menaiel", postalCode: "35004" },
      { name: "Naciria", postalCode: "35005" },
      { name: "Hammadi", postalCode: "35006" },
      { name: "Corso", postalCode: "35007" },
      { name: "Tidjelabine", postalCode: "35008" },
      { name: "Ouled Moussa", postalCode: "35009" },
      { name: "Baghlia", postalCode: "35010" },
      { name: "Larbatache", postalCode: "35011" },
      { name: "Timezrit", postalCode: "35012" },
      { name: "Isser", postalCode: "35013" },
      { name: "Si Mustapha", postalCode: "35014" },
      { name: "Afir", postalCode: "35015" },
    ],
  },
  {
    wilaya: "El Tarf",
    communes: [
      { name: "El Tarf", postalCode: "36000" },
      { name: "El Kala", postalCode: "36001" },
      { name: "Bouhadjar", postalCode: "36002" },
      { name: "Ben M'Hidi", postalCode: "36003" },
      { name: "Besbes", postalCode: "36004" },
      { name: "Dréan", postalCode: "36005" },
      { name: "Ain El Assel", postalCode: "36006" },
      { name: "Bouteldja", postalCode: "36007" },
      { name: "Bougous", postalCode: "36008" },
      { name: "Zerizer", postalCode: "36009" },
      { name: "Chihani", postalCode: "36010" },
      { name: "Lac des Oiseaux", postalCode: "36011" },
      { name: "Raml Souk", postalCode: "36012" },
    ],
  },
  {
    wilaya: "Tindouf",
    communes: [
      { name: "Tindouf", postalCode: "37000" },
      { name: "Oum El Assel", postalCode: "37001" },
    ],
  },
  {
    wilaya: "Tissemsilt",
    communes: [
      { name: "Tissemsilt", postalCode: "38000" },
      { name: "Theniet El Had", postalCode: "38001" },
      { name: "Bordj Bou Naama", postalCode: "38002" },
      { name: "Lardjem", postalCode: "38003" },
      { name: "Khemisti", postalCode: "38004" },
      { name: "Layoune", postalCode: "38005" },
      { name: "Ammari", postalCode: "38006" },
      { name: "Bordj Emir Abdelkader", postalCode: "38007" },
      { name: "Ouled Bessam", postalCode: "38008" },
      { name: "Tamalaht", postalCode: "38009" },
      { name: "Sidi Lantri", postalCode: "38010" },
    ],
  },
  {
    wilaya: "El Oued",
    communes: [
      { name: "El Oued", postalCode: "39000" },
      { name: "Guemar", postalCode: "39001" },
      { name: "Robbah", postalCode: "39002" },
      { name: "Debila", postalCode: "39003" },
      { name: "Hassani Abdelkrim", postalCode: "39004" },
      { name: "Bayadha", postalCode: "39005" },
      { name: "Djamaa", postalCode: "39006" },
      { name: "Oum Touyour", postalCode: "39007" },
      { name: "Kouinine", postalCode: "39008" },
      { name: "Reguiba", postalCode: "39009" },
      { name: "Magrane", postalCode: "39010" },
      { name: "Oued El Alenda", postalCode: "39011" },
      { name: "N'Sigha", postalCode: "39012" },
    ],
  },
  {
    wilaya: "Khenchela",
    communes: [
      { name: "Khenchela", postalCode: "40000" },
      { name: "Kais", postalCode: "40001" },
      { name: "Baghai", postalCode: "40002" },
      { name: "Chechar", postalCode: "40003" },
      { name: "El Hamma", postalCode: "40004" },
      { name: "Bouhmama", postalCode: "40005" },
      { name: "El Oueldja", postalCode: "40006" },
      { name: "Taouzianat", postalCode: "40007" },
      { name: "Ain Touila", postalCode: "40008" },
      { name: "M'Sara", postalCode: "40009" },
      { name: "Babar", postalCode: "40010" },
      { name: "Ouled Rechache", postalCode: "40011" },
    ],
  },
  {
    wilaya: "Souk Ahras",
    communes: [
      { name: "Souk Ahras", postalCode: "41000" },
      { name: "Sedrata", postalCode: "41001" },
      { name: "M'Daourouch", postalCode: "41002" },
      { name: "Taoura", postalCode: "41003" },
      { name: "Ain Zana", postalCode: "41004" },
      { name: "Mechroha", postalCode: "41005" },
      { name: "Ouled Driss", postalCode: "41006" },
      { name: "Oum El Adhaim", postalCode: "41007" },
      { name: "Haddada", postalCode: "41008" },
      { name: "Merahna", postalCode: "41009" },
      { name: "Zaarouria", postalCode: "41010" },
    ],
  },
  {
    wilaya: "Tipaza",
    communes: [
      { name: "Tipaza", postalCode: "42000" },
      { name: "Koléa", postalCode: "42001" },
      { name: "Hadjout", postalCode: "42002" },
      { name: "Cherchell", postalCode: "42003" },
      { name: "Bou Ismaïl", postalCode: "42004" },
      { name: "Fouka", postalCode: "42005" },
      { name: "Gouraya", postalCode: "42006" },
      { name: "Damous", postalCode: "42007" },
      { name: "Ain Tagourait", postalCode: "42008" },
      { name: "Sidi Amar", postalCode: "42009" },
      { name: "Nador", postalCode: "42010" },
      { name: "Attatba", postalCode: "42011" },
      { name: "Sidi Rached", postalCode: "42012" },
      { name: "Larhat", postalCode: "42013" },
      { name: "Messelmoun", postalCode: "42014" },
      { name: "Ain Tagourait", postalCode: "42015" },
    ],
  },
  {
    wilaya: "Mila",
    communes: [
      { name: "Mila", postalCode: "43000" },
      { name: "Ferdjioua", postalCode: "43001" },
      { name: "Chelghoum Laïd", postalCode: "43002" },
      { name: "Grarem Gouga", postalCode: "43003" },
      { name: "Oued Athmenia", postalCode: "43004" },
      { name: "Rouached", postalCode: "43005" },
      { name: "Ain Beida Harriche", postalCode: "43006" },
      { name: "Teleghma", postalCode: "43007" },
      { name: "Oued Seguen", postalCode: "43008" },
      { name: "Bouhatem", postalCode: "43009" },
      { name: "Benyahia Abderrahmane", postalCode: "43010" },
      { name: "Tassadane Haddada", postalCode: "43011" },
    ],
  },
  {
    wilaya: "Aïn Defla",
    communes: [
      { name: "Aïn Defla", postalCode: "44000" },
      { name: "Miliana", postalCode: "44001" },
      { name: "Khemis Miliana", postalCode: "44002" },
      { name: "El Attaf", postalCode: "44003" },
      { name: "Djelida", postalCode: "44004" },
      { name: "Hammam Righa", postalCode: "44005" },
      { name: "Rouina", postalCode: "44006" },
      { name: "Bourached", postalCode: "44007" },
      { name: "Ain Lechiakh", postalCode: "44008" },
      { name: "El Abadia", postalCode: "44009" },
      { name: "Djendel", postalCode: "44010" },
      { name: "Bordj Emir Khaled", postalCode: "44011" },
      { name: "Ain Benian", postalCode: "44012" },
      { name: "Ain Soltane", postalCode: "44013" },
    ],
  },
  {
    wilaya: "Naâma",
    communes: [
      { name: "Naâma", postalCode: "45000" },
      { name: "Mecheria", postalCode: "45001" },
      { name: "Ain Sefra", postalCode: "45002" },
      { name: "Moghrar", postalCode: "45003" },
      { name: "Sfissifa", postalCode: "45004" },
      { name: "Djenien Bourezg", postalCode: "45005" },
      { name: "Asla", postalCode: "45006" },
      { name: "Kasdir", postalCode: "45007" },
      { name: "Tiout", postalCode: "45008" },
    ],
  },
  {
    wilaya: "Aïn Témouchent",
    communes: [
      { name: "Aïn Témouchent", postalCode: "46000" },
      { name: "Hammam Bou Hadjar", postalCode: "46001" },
      { name: "Beni Saf", postalCode: "46002" },
      { name: "El Amria", postalCode: "46003" },
      { name: "El Malah", postalCode: "46004" },
      { name: "Oulhaça El Gheraba", postalCode: "46005" },
      { name: "Ain Kihal", postalCode: "46006" },
      { name: "Aghlal", postalCode: "46007" },
      { name: "Ain El Arbaa", postalCode: "46008" },
      { name: "Hassi El Ghella", postalCode: "46009" },
      { name: "Oued Berkeche", postalCode: "46010" },
    ],
  },
  {
    wilaya: "Ghardaïa",
    communes: [
      { name: "Ghardaïa", postalCode: "47000" },
      { name: "Metlili", postalCode: "47001" },
      { name: "El Guerrara", postalCode: "47002" },
      { name: "Berriane", postalCode: "47003" },
      { name: "Dhayet Bendhahoua", postalCode: "47004" },
      { name: "Zelfana", postalCode: "47005" },
      { name: "Bounoura", postalCode: "47006" },
      { name: "El Atteuf", postalCode: "47007" },
      { name: "Mansoura", postalCode: "47008" },
      { name: "Hassi Gara", postalCode: "47009" },
    ],
  },
  {
    wilaya: "Relizane",
    communes: [
      { name: "Relizane", postalCode: "48000" },
      { name: "Oued Rhiou", postalCode: "48001" },
      { name: "Mazouna", postalCode: "48002" },
      { name: "Yellel", postalCode: "48003" },
      { name: "Ain Tarek", postalCode: "48004" },
      { name: "Mendes", postalCode: "48005" },
      { name: "Sidi M'Hamed Ben Ali", postalCode: "48006" },
      { name: "Djidiouia", postalCode: "48007" },
      { name: "Ramka", postalCode: "48008" },
      { name: "Ammi Moussa", postalCode: "48009" },
      { name: "Zemmoura", postalCode: "48010" },
      { name: "El Matmar", postalCode: "48011" },
      { name: "Had Echkalla", postalCode: "48012" },
      { name: "Sidi Khettab", postalCode: "48013" },
    ],
  },
  {
    wilaya: "Timimoun",
    communes: [
      { name: "Timimoun", postalCode: "49000" },
      { name: "Charouine", postalCode: "49001" },
      { name: "Aougrout", postalCode: "49002" },
      { name: "Ouled Said", postalCode: "49003" },
      { name: "Tinerkouk", postalCode: "49004" },
      { name: "Deldoul", postalCode: "49005" },
      { name: "Metarfa", postalCode: "49006" },
    ],
  },
  {
    wilaya: "Bordj Badji Mokhtar",
    communes: [
      { name: "Bordj Badji Mokhtar", postalCode: "50000" },
      { name: "Timiaouine", postalCode: "50001" },
    ],
  },
  {
    wilaya: "Ouled Djellal",
    communes: [
      { name: "Ouled Djellal", postalCode: "51000" },
      { name: "Sidi Khaled", postalCode: "51001" },
      { name: "Doucen", postalCode: "51002" },
      { name: "Chaiba", postalCode: "51003" },
      { name: "Ras El Miaad", postalCode: "51004" },
    ],
  },
  {
    wilaya: "Béni Abbès",
    communes: [
      { name: "Béni Abbès", postalCode: "52000" },
      { name: "Igli", postalCode: "52001" },
      { name: "El Ouata", postalCode: "52002" },
      { name: "Kerzaz", postalCode: "52003" },
      { name: "Tabelbala", postalCode: "52004" },
      { name: "Ouled Khoudir", postalCode: "52005" },
      { name: "Tamtert", postalCode: "52006" },
    ],
  },
  {
    wilaya: "In Salah",
    communes: [
      { name: "In Salah", postalCode: "53000" },
      { name: "In Ghar", postalCode: "53001" },
      { name: "Foggaret Ezzaouia", postalCode: "53002" },
      { name: "Ain El Hadjel", postalCode: "53003" },
      { name: "Hassi El Gara", postalCode: "53004" },
    ],
  },
  {
    wilaya: "In Guezzam",
    communes: [
      { name: "In Guezzam", postalCode: "54000" },
      { name: "Tin Zaouatine", postalCode: "54001" },
      { name: "Assamaka", postalCode: "54002" },
    ],
  },
  {
    wilaya: "Touggourt",
    communes: [
      { name: "Touggourt", postalCode: "55000" },
      { name: "Temacine", postalCode: "55001" },
      { name: "Megarine", postalCode: "55002" },
      { name: "Taibet", postalCode: "55003" },
      { name: "Nezla", postalCode: "55004" },
      { name: "Zaouia El Abidia", postalCode: "55005" },
      { name: "Tebesbest", postalCode: "55006" },
      { name: "Blidet Amor", postalCode: "55007" },
    ],
  },
  {
    wilaya: "Djanet",
    communes: [
      { name: "Djanet", postalCode: "56000" },
      { name: "Bordj El Haoues", postalCode: "56001" },
      { name: "In Abangarit", postalCode: "56002" },
    ],
  },
  {
    wilaya: "El M'Ghair",
    communes: [
      { name: "El M'Ghair", postalCode: "57000" },
      { name: "Oum Touyour", postalCode: "57001" },
      { name: "Still", postalCode: "57002" },
      { name: "Djamaa", postalCode: "57003" },
      { name: "Sidi Khaled", postalCode: "57004" },
    ],
  },
  {
    wilaya: "El Meniaa",
    communes: [
      { name: "El Meniaa", postalCode: "58000" },
      { name: "Hassi Gara", postalCode: "58001" },
      { name: "Hassi Fehal", postalCode: "58002" },
    ],
  },
];

/* Helper: get communes for a given wilaya */
export function getCommunesForWilaya(wilayaName: string): Commune[] {
  const found = ALGERIA_DATA.find((w) => w.wilaya === wilayaName);
  return found ? found.communes : [];
}

/* Helper: get all wilaya names */
export function getWilayaNames(): string[] {
  return ALGERIA_DATA.map((w) => w.wilaya);
}
